---
# tasks file for nginx
- name: NGINX | Install NGINX package
  apt:
    name: nginx
    state: latest
  notify:
    - restart_nginx
- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: 
    - reload_nginx